// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXhfYBTjgcc8ebfBaz7SoyKwimlcE_BTQ',
    appId: '1:558116573581:web:bcdd81d175a72ea4f12dc4',
    messagingSenderId: '558116573581',
    projectId: 'peramoneykwarta',
    authDomain: 'peramoneykwarta.firebaseapp.com',
    storageBucket: 'peramoneykwarta.firebasestorage.app',
    measurementId: 'G-9KVW49Q4QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8iN0l4nOFBEVd0w_OYjOg_aHab9eo4H8',
    appId: '1:558116573581:android:86e310a6494a8c24f12dc4',
    messagingSenderId: '558116573581',
    projectId: 'peramoneykwarta',
    storageBucket: 'peramoneykwarta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyA60tVsecEx0_7QTbdPeLPnNTGFVZHTQ',
    appId: '1:558116573581:ios:be22fea921252d96f12dc4',
    messagingSenderId: '558116573581',
    projectId: 'peramoneykwarta',
    storageBucket: 'peramoneykwarta.firebasestorage.app',
    iosBundleId: 'com.example.peramoneykwarta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyA60tVsecEx0_7QTbdPeLPnNTGFVZHTQ',
    appId: '1:558116573581:ios:be22fea921252d96f12dc4',
    messagingSenderId: '558116573581',
    projectId: 'peramoneykwarta',
    storageBucket: 'peramoneykwarta.firebasestorage.app',
    iosBundleId: 'com.example.peramoneykwarta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXhfYBTjgcc8ebfBaz7SoyKwimlcE_BTQ',
    appId: '1:558116573581:web:509dcf14d6f970a0f12dc4',
    messagingSenderId: '558116573581',
    projectId: 'peramoneykwarta',
    authDomain: 'peramoneykwarta.firebaseapp.com',
    storageBucket: 'peramoneykwarta.firebasestorage.app',
    measurementId: 'G-V8NZXYJTCN',
  );
}
